import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button } from "../components/atoms/Button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button
        label="ボタン"
        size={"large"}
        primary={false}
        onClick={(e) => {
          console.log(e.target.innerText);
        }}
      />
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className="group">
            Welcome! to{" "}
            <a className="" href="https://nextjs.org">
              Next.js!
            </a>
          </h1>
          <div className="group border-indigo-500 hover:bg-white hover:shadow-lg hover:border-transparent ...">
            <p className="text-indigo-600 group-hover:text-gray-900">
              New Project
            </p>
            <p className="text-indigo-500 group-hover:text-gray-500">
              Create a new project from a variety of starting templates.
            </p>
          </div>
          <p>
            Get started by editing <code>pages/index.js</code>
          </p>

          <div>
            <a href="https://nextjs.org/docs">
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn">
              <h2 className="text-red-400">Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a href="https://github.com/vercel/next.js/tree/master/examples">
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
